In [6]:
import pymongo
import pandas as pd
import numpy as np

In [7]:
from pymongo import MongoClient

conn = MongoClient(host='127.0.0.1', port=27017)  # 实例化MongoClient
db = conn.get_database('lianjia')  # 连接到Lianjia数据库

zufang = db.get_collection('zufang_gz') # 连接到集合zufang
mon_data = zufang.find()  # 查询这个集合下的所有记录

In [8]:
lianjia_df=pd.DataFrame(list(mon_data))

In [9]:
lianjia_df.head(5)

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>_id</th>
      <th>dataDistributionType</th>
      <th>district</th>
      <th>microdistrict</th>
      <th>community</th>
      <th>area</th>
      <th>orientation</th>
      <th>houseType</th>
      <th>tags</th>
      <th>title</th>
      <th>price</th>
      <th>city</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>5e5cff1744303bb255b0f899</td>
      <td>0</td>
      <td>增城</td>
      <td>沙村</td>
      <td>新塘新世界花园万象苑</td>
      <td>117</td>
      <td>南</td>
      <td>3室1厅2卫</td>
      <td>[近地铁, 双卫生间]</td>
      <td>整租·新塘新世界花园万象苑 3室1厅 南</td>
      <td>2500</td>
      <td>广州</td>
    </tr>
    <tr>
      <th>1</th>
      <td>5e5cff1744303bb255b0f89a</td>
      <td>0</td>
      <td>增城</td>
      <td>沙村</td>
      <td>广州海伦堡</td>
      <td>120</td>
      <td>西南</td>
      <td>4室2厅2卫</td>
      <td>[精装, 双卫生间, 随时看房]</td>
      <td>整租·广州海伦堡 4室2厅 错层 西南</td>
      <td>2300</td>
      <td>广州</td>
    </tr>
    <tr>
      <th>2</th>
      <td>5e5cff1744303bb255b0f89b</td>
      <td>0</td>
      <td>增城</td>
      <td>沙村</td>
      <td>广州海伦堡</td>
      <td>110</td>
      <td>北</td>
      <td>3室2厅2卫</td>
      <td>[双卫生间, 随时看房]</td>
      <td>整租·广州海伦堡 3室2厅 北</td>
      <td>2500</td>
      <td>广州</td>
    </tr>
    <tr>
      <th>3</th>
      <td>5e5cff1744303bb255b0f89c</td>
      <td>0</td>
      <td>增城</td>
      <td>沙村</td>
      <td>广州海伦堡</td>
      <td>124</td>
      <td>南</td>
      <td>4室2厅2卫</td>
      <td>[双卫生间]</td>
      <td>整租·广州海伦堡 4室2厅 南</td>
      <td>2300</td>
      <td>广州</td>
    </tr>
    <tr>
      <th>4</th>
      <td>5e5cff1744303bb255b0f89d</td>
      <td>0</td>
      <td>增城</td>
      <td>沙村</td>
      <td>广州海伦堡</td>
      <td>89</td>
      <td>西南</td>
      <td>3室2厅2卫</td>
      <td>[双卫生间]</td>
      <td>整租·广州海伦堡 3室2厅 西南</td>
      <td>2500</td>
      <td>广州</td>
    </tr>
  </tbody>
</table>
</div>

In [10]:
df=lianjia_df.copy()
df=df.drop(columns='_id')
df=df.drop(columns='title')

In [11]:
df['perPrice']=df['price']/df['area']
df['hall']=df['houseType'].str[0]
df['bed']=df['houseType'].str[2]
df['bath']=df['houseType'].str[4]
col = ['city','district','microdistrict','community','price',
       'perPrice','area','orientation','orientation','tags','hall','bed','bath']
df

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>dataDistributionType</th>
      <th>district</th>
      <th>microdistrict</th>
      <th>community</th>
      <th>area</th>
      <th>orientation</th>
      <th>houseType</th>
      <th>tags</th>
      <th>price</th>
      <th>city</th>
      <th>perPrice</th>
      <th>hall</th>
      <th>bed</th>
      <th>bath</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>0</td>
      <td>增城</td>
      <td>沙村</td>
      <td>新塘新世界花园万象苑</td>
      <td>117</td>
      <td>南</td>
      <td>3室1厅2卫</td>
      <td>[近地铁, 双卫生间]</td>
      <td>2500</td>
      <td>广州</td>
      <td>21.367521</td>
      <td>3</td>
      <td>1</td>
      <td>2</td>
    </tr>
    <tr>
      <th>1</th>
      <td>0</td>
      <td>增城</td>
      <td>沙村</td>
      <td>广州海伦堡</td>
      <td>120</td>
      <td>西南</td>
      <td>4室2厅2卫</td>
      <td>[精装, 双卫生间, 随时看房]</td>
      <td>2300</td>
      <td>广州</td>
      <td>19.166667</td>
      <td>4</td>
      <td>2</td>
      <td>2</td>
    </tr>
    <tr>
      <th>2</th>
      <td>0</td>
      <td>增城</td>
      <td>沙村</td>
      <td>广州海伦堡</td>
      <td>110</td>
      <td>北</td>
      <td>3室2厅2卫</td>
      <td>[双卫生间, 随时看房]</td>
      <td>2500</td>
      <td>广州</td>
      <td>22.727273</td>
      <td>3</td>
      <td>2</td>
      <td>2</td>
    </tr>
    <tr>
      <th>3</th>
      <td>0</td>
      <td>增城</td>
      <td>沙村</td>
      <td>广州海伦堡</td>
      <td>124</td>
      <td>南</td>
      <td>4室2厅2卫</td>
      <td>[双卫生间]</td>
      <td>2300</td>
      <td>广州</td>
      <td>18.548387</td>
      <td>4</td>
      <td>2</td>
      <td>2</td>
    </tr>
    <tr>
      <th>4</th>
      <td>0</td>
      <td>增城</td>
      <td>沙村</td>
      <td>广州海伦堡</td>
      <td>89</td>
      <td>西南</td>
      <td>3室2厅2卫</td>
      <td>[双卫生间]</td>
      <td>2500</td>
      <td>广州</td>
      <td>28.089888</td>
      <td>3</td>
      <td>2</td>
      <td>2</td>
    </tr>
    <tr>
      <th>...</th>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
    </tr>
    <tr>
      <th>53385</th>
      <td>0</td>
      <td>增城</td>
      <td>石滩镇</td>
      <td>碧桂园琥珀湾</td>
      <td>97</td>
      <td>南</td>
      <td>3室1厅2卫</td>
      <td>[双卫生间]</td>
      <td>1900</td>
      <td>广州</td>
      <td>19.587629</td>
      <td>3</td>
      <td>1</td>
      <td>2</td>
    </tr>
    <tr>
      <th>53386</th>
      <td>0</td>
      <td>增城</td>
      <td>石滩镇</td>
      <td>绿湖国际城</td>
      <td>116</td>
      <td>南</td>
      <td>3室2厅1卫</td>
      <td>NaN</td>
      <td>2200</td>
      <td>广州</td>
      <td>18.965517</td>
      <td>3</td>
      <td>2</td>
      <td>1</td>
    </tr>
    <tr>
      <th>53387</th>
      <td>0</td>
      <td>增城</td>
      <td>石滩镇</td>
      <td>绿湖国际城</td>
      <td>107</td>
      <td>西南</td>
      <td>3室2厅1卫</td>
      <td>[新上, 随时看房]</td>
      <td>1500</td>
      <td>广州</td>
      <td>14.018692</td>
      <td>3</td>
      <td>2</td>
      <td>1</td>
    </tr>
    <tr>
      <th>53388</th>
      <td>0</td>
      <td>增城</td>
      <td>石滩镇</td>
      <td>碧桂园琥珀湾</td>
      <td>97</td>
      <td>南</td>
      <td>3室2厅2卫</td>
      <td>[双卫生间]</td>
      <td>1500</td>
      <td>广州</td>
      <td>15.463918</td>
      <td>3</td>
      <td>2</td>
      <td>2</td>
    </tr>
    <tr>
      <th>53389</th>
      <td>0</td>
      <td>增城</td>
      <td>石滩镇</td>
      <td>绿湖国际城</td>
      <td>80</td>
      <td>东</td>
      <td>2室2厅1卫</td>
      <td>[新上]</td>
      <td>1300</td>
      <td>广州</td>
      <td>16.250000</td>
      <td>2</td>
      <td>2</td>
      <td>1</td>
    </tr>
  </tbody>
</table>
<p>53390 rows × 14 columns</p>
</div>

In [39]:

df_house_count=df.loc[(df['dataDistributionType']==0),:].groupby('district')['price'].count().sort_values(ascending=False).to_frame().reset_index()
df_apartment_count=df.loc[(df['dataDistributionType']==1),:].groupby('district')['price'].count().sort_values(ascending=False).to_frame().reset_index()
df_house_mean=df.loc[(df['dataDistributionType']==1),:].groupby('district')['perPrice'].mean().round(1) .sort_values(ascending=False).to_frame().reset_index()
df_apartment_mean=df.loc[(df['dataDistributionType']==0),:].groupby('district')['perPrice'].mean().round(1) .sort_values(ascending=False).to_frame().reset_index()
print(df_house_mean)

   district  perPrice
0        越秀     127.1
1        天河      84.9
2        从化      75.7
3        海珠      66.3
4        增城      61.3
5        白云      57.6
6        南沙      49.5
7        荔湾      49.3
8        番禺      47.1
9        黄埔      45.3
10       花都      33.7

In [29]:
from pyecharts.charts import Bar

In [32]:

bar = Bar()
bar.add_xaxis(list(df_house_count['district']))
bar.add_yaxis("个人房源", list(df_house_count['price']))
bar.add_yaxis("公寓", list(df_apartment_count['price']))
bar.set_global_opts(title_opts=opts.TitleOpts(title="广州出租房源信息数量"))
bar.render("./lianjiaSpider/Analyse/html/gz.html")

'F:\\作业\\毕业设计\\项目\\lianjiaSpider\\lianjiaSpider\\Analyse\\html\\gz.html'

In [38]:
bar = Bar()
bar.add_xaxis(list(df_house_count['district']))
bar.add_yaxis("个人房源", list(df_house_mean['perPrice']))
bar.add_yaxis("公寓", list(df_apartment_mean['perPrice']))
bar.set_global_opts(title_opts=opts.TitleOpts(title="广州租房月租均价 米/平方米"))
bar.render("./lianjiaSpider/Analyse/html/gz_price.html")

'F:\\作业\\毕业设计\\项目\\lianjiaSpider\\lianjiaSpider\\Analyse\\html\\gz_price.html'

In [55]:

print(df.count())
a=df.dropna(subset = ['price'])
print(a.count())

dataDistributionType    53390
district                53390
microdistrict           53390
community               48834
area                    53390
orientation             48834
houseType               53390
tags                    43854
price                   53390
city                    53390
perPrice                53390
hall                    53255
bed                     53255
bath                    53255
dtype: int64
dataDistributionType    53390
district                53390
microdistrict           53390
community               48834
area                    53390
orientation             48834
houseType               53390
tags                    43854
price                   53390
city                    53390
perPrice                53390
hall                    53255
bed                     53255
bath                    53255
dtype: int64